//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ArrayOfPaymentTerm {
    
    private ArrayOfPaymentTermPaymentTerm[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PaymentTerm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ArrayOfPaymentTermPaymentTerm[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ArrayOfPaymentTermPaymentTerm {
    
    private System.Nullable<bool> customField_Boolean1Field;
    
    private bool customField_Boolean1FieldSpecified;
    
    private System.Nullable<bool> customField_Boolean2Field;
    
    private bool customField_Boolean2FieldSpecified;
    
    private System.Nullable<bool> customField_Boolean3Field;
    
    private bool customField_Boolean3FieldSpecified;
    
    private System.Nullable<bool> customField_Boolean4Field;
    
    private bool customField_Boolean4FieldSpecified;
    
    private System.Nullable<bool> customField_Boolean5Field;
    
    private bool customField_Boolean5FieldSpecified;
    
    private System.Nullable<System.DateTime> customField_DateTime1Field;
    
    private bool customField_DateTime1FieldSpecified;
    
    private System.Nullable<System.DateTime> customField_DateTime2Field;
    
    private bool customField_DateTime2FieldSpecified;
    
    private System.Nullable<System.DateTime> customField_DateTime3Field;
    
    private bool customField_DateTime3FieldSpecified;
    
    private System.Nullable<System.DateTime> customField_DateTime4Field;
    
    private bool customField_DateTime4FieldSpecified;
    
    private System.Nullable<System.DateTime> customField_DateTime5Field;
    
    private bool customField_DateTime5FieldSpecified;
    
    private System.Nullable<decimal> customField_Numeric1Field;
    
    private bool customField_Numeric1FieldSpecified;
    
    private System.Nullable<decimal> customField_Numeric2Field;
    
    private bool customField_Numeric2FieldSpecified;
    
    private System.Nullable<decimal> customField_Numeric3Field;
    
    private bool customField_Numeric3FieldSpecified;
    
    private System.Nullable<decimal> customField_Numeric4Field;
    
    private bool customField_Numeric4FieldSpecified;
    
    private System.Nullable<decimal> customField_Numeric5Field;
    
    private bool customField_Numeric5FieldSpecified;
    
    private string customField_Text1Field;
    
    private string customField_Text2Field;
    
    private string customField_Text3Field;
    
    private string customField_Text4Field;
    
    private string customField_Text5Field;
    
    private string companyIdField;
    
    private string descriptionField;
    
    private string erpSourceIdField;
    
    private bool isActiveField;
    
    private bool isActiveFieldSpecified;
    
    private System.Nullable<int> numberOfDaysField;
    
    private bool numberOfDaysFieldSpecified;
    
    private System.Nullable<int> numberOfFreeMonthsField;
    
    private bool numberOfFreeMonthsFieldSpecified;
    
    private string paymentTermIdField;
    
    private ArrayOfPaymentTermPaymentTermStartDate startDateField;
    
    private ArrayOfPaymentTermPaymentTermPaymentTermLine[] linesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<bool> CustomField_Boolean1 {
        get {
            return this.customField_Boolean1Field;
        }
        set {
            this.customField_Boolean1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomField_Boolean1Specified {
        get {
            return this.customField_Boolean1FieldSpecified;
        }
        set {
            this.customField_Boolean1FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<bool> CustomField_Boolean2 {
        get {
            return this.customField_Boolean2Field;
        }
        set {
            this.customField_Boolean2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomField_Boolean2Specified {
        get {
            return this.customField_Boolean2FieldSpecified;
        }
        set {
            this.customField_Boolean2FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<bool> CustomField_Boolean3 {
        get {
            return this.customField_Boolean3Field;
        }
        set {
            this.customField_Boolean3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomField_Boolean3Specified {
        get {
            return this.customField_Boolean3FieldSpecified;
        }
        set {
            this.customField_Boolean3FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<bool> CustomField_Boolean4 {
        get {
            return this.customField_Boolean4Field;
        }
        set {
            this.customField_Boolean4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomField_Boolean4Specified {
        get {
            return this.customField_Boolean4FieldSpecified;
        }
        set {
            this.customField_Boolean4FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<bool> CustomField_Boolean5 {
        get {
            return this.customField_Boolean5Field;
        }
        set {
            this.customField_Boolean5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomField_Boolean5Specified {
        get {
            return this.customField_Boolean5FieldSpecified;
        }
        set {
            this.customField_Boolean5FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> CustomField_DateTime1 {
        get {
            return this.customField_DateTime1Field;
        }
        set {
            this.customField_DateTime1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomField_DateTime1Specified {
        get {
            return this.customField_DateTime1FieldSpecified;
        }
        set {
            this.customField_DateTime1FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> CustomField_DateTime2 {
        get {
            return this.customField_DateTime2Field;
        }
        set {
            this.customField_DateTime2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomField_DateTime2Specified {
        get {
            return this.customField_DateTime2FieldSpecified;
        }
        set {
            this.customField_DateTime2FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> CustomField_DateTime3 {
        get {
            return this.customField_DateTime3Field;
        }
        set {
            this.customField_DateTime3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomField_DateTime3Specified {
        get {
            return this.customField_DateTime3FieldSpecified;
        }
        set {
            this.customField_DateTime3FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> CustomField_DateTime4 {
        get {
            return this.customField_DateTime4Field;
        }
        set {
            this.customField_DateTime4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomField_DateTime4Specified {
        get {
            return this.customField_DateTime4FieldSpecified;
        }
        set {
            this.customField_DateTime4FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> CustomField_DateTime5 {
        get {
            return this.customField_DateTime5Field;
        }
        set {
            this.customField_DateTime5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomField_DateTime5Specified {
        get {
            return this.customField_DateTime5FieldSpecified;
        }
        set {
            this.customField_DateTime5FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<decimal> CustomField_Numeric1 {
        get {
            return this.customField_Numeric1Field;
        }
        set {
            this.customField_Numeric1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomField_Numeric1Specified {
        get {
            return this.customField_Numeric1FieldSpecified;
        }
        set {
            this.customField_Numeric1FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<decimal> CustomField_Numeric2 {
        get {
            return this.customField_Numeric2Field;
        }
        set {
            this.customField_Numeric2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomField_Numeric2Specified {
        get {
            return this.customField_Numeric2FieldSpecified;
        }
        set {
            this.customField_Numeric2FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<decimal> CustomField_Numeric3 {
        get {
            return this.customField_Numeric3Field;
        }
        set {
            this.customField_Numeric3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomField_Numeric3Specified {
        get {
            return this.customField_Numeric3FieldSpecified;
        }
        set {
            this.customField_Numeric3FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<decimal> CustomField_Numeric4 {
        get {
            return this.customField_Numeric4Field;
        }
        set {
            this.customField_Numeric4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomField_Numeric4Specified {
        get {
            return this.customField_Numeric4FieldSpecified;
        }
        set {
            this.customField_Numeric4FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<decimal> CustomField_Numeric5 {
        get {
            return this.customField_Numeric5Field;
        }
        set {
            this.customField_Numeric5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomField_Numeric5Specified {
        get {
            return this.customField_Numeric5FieldSpecified;
        }
        set {
            this.customField_Numeric5FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string CustomField_Text1 {
        get {
            return this.customField_Text1Field;
        }
        set {
            this.customField_Text1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string CustomField_Text2 {
        get {
            return this.customField_Text2Field;
        }
        set {
            this.customField_Text2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string CustomField_Text3 {
        get {
            return this.customField_Text3Field;
        }
        set {
            this.customField_Text3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string CustomField_Text4 {
        get {
            return this.customField_Text4Field;
        }
        set {
            this.customField_Text4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string CustomField_Text5 {
        get {
            return this.customField_Text5Field;
        }
        set {
            this.customField_Text5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CompanyId {
        get {
            return this.companyIdField;
        }
        set {
            this.companyIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ErpSourceId {
        get {
            return this.erpSourceIdField;
        }
        set {
            this.erpSourceIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool IsActive {
        get {
            return this.isActiveField;
        }
        set {
            this.isActiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsActiveSpecified {
        get {
            return this.isActiveFieldSpecified;
        }
        set {
            this.isActiveFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<int> NumberOfDays {
        get {
            return this.numberOfDaysField;
        }
        set {
            this.numberOfDaysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NumberOfDaysSpecified {
        get {
            return this.numberOfDaysFieldSpecified;
        }
        set {
            this.numberOfDaysFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<int> NumberOfFreeMonths {
        get {
            return this.numberOfFreeMonthsField;
        }
        set {
            this.numberOfFreeMonthsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NumberOfFreeMonthsSpecified {
        get {
            return this.numberOfFreeMonthsFieldSpecified;
        }
        set {
            this.numberOfFreeMonthsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PaymentTermId {
        get {
            return this.paymentTermIdField;
        }
        set {
            this.paymentTermIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ArrayOfPaymentTermPaymentTermStartDate StartDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("PaymentTermLine", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ArrayOfPaymentTermPaymentTermPaymentTermLine[] Lines {
        get {
            return this.linesField;
        }
        set {
            this.linesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ArrayOfPaymentTermPaymentTermStartDate {
    
    private string typeField;
    
    private System.Nullable<int> fixedDayField;
    
    private bool fixedDayFieldSpecified;
    
    private System.Nullable<int> numberOfMonthsField;
    
    private bool numberOfMonthsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<int> FixedDay {
        get {
            return this.fixedDayField;
        }
        set {
            this.fixedDayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FixedDaySpecified {
        get {
            return this.fixedDayFieldSpecified;
        }
        set {
            this.fixedDayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<int> NumberOfMonths {
        get {
            return this.numberOfMonthsField;
        }
        set {
            this.numberOfMonthsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NumberOfMonthsSpecified {
        get {
            return this.numberOfMonthsFieldSpecified;
        }
        set {
            this.numberOfMonthsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ArrayOfPaymentTermPaymentTermPaymentTermLine {
    
    private decimal cashDiscountPercentageField;
    
    private bool cashDiscountPercentageFieldSpecified;
    
    private bool endOfMonthField;
    
    private bool endOfMonthFieldSpecified;
    
    private System.Nullable<int> fixedPaymentDayField;
    
    private bool fixedPaymentDayFieldSpecified;
    
    private int numberOfDaysField;
    
    private int numberOfMonthsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal CashDiscountPercentage {
        get {
            return this.cashDiscountPercentageField;
        }
        set {
            this.cashDiscountPercentageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CashDiscountPercentageSpecified {
        get {
            return this.cashDiscountPercentageFieldSpecified;
        }
        set {
            this.cashDiscountPercentageFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool EndOfMonth {
        get {
            return this.endOfMonthField;
        }
        set {
            this.endOfMonthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EndOfMonthSpecified {
        get {
            return this.endOfMonthFieldSpecified;
        }
        set {
            this.endOfMonthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<int> FixedPaymentDay {
        get {
            return this.fixedPaymentDayField;
        }
        set {
            this.fixedPaymentDayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FixedPaymentDaySpecified {
        get {
            return this.fixedPaymentDayFieldSpecified;
        }
        set {
            this.fixedPaymentDayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int NumberOfDays {
        get {
            return this.numberOfDaysField;
        }
        set {
            this.numberOfDaysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int NumberOfMonths {
        get {
            return this.numberOfMonthsField;
        }
        set {
            this.numberOfMonthsField = value;
        }
    }
}
